services:
  service-template:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "5555:5555"
##    security_opt:
##      - label:disable ## for native ==> needs investigation about security issues