quarkus.http.root-path=/@project.artifactId@
quarkus.log.level=DEBUG
fakher=@fakher@
quarkus.vault.url=${VAULT_URL:}
quarkus.vault.secret-config-kv-path=@vault.secret.config.path@
quarkus.vault.kv-secret-engine-mount-path=@vault.kv.mount.path@
quarkus.vault.authentication.client-token=${VAULT_TOKEN:}
