quarkus.http.port=5555
quarkus.grpc.server.port=9000
quarkus.devservices.enabled=false
quarkus.datasource.devservices.enabled=false
quarkus.vault.devservices.enabled=false
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{2.}:%L] (%t) %s%e%n
quarkus.micrometer.export.json.enabled=true
quarkus.micrometer.export.json.path=metrics/json
quarkus.micrometer.export.prometheus.path=metrics
quarkus.vault.authentication.client-token=${VAULT_TOKEN:}
