fakher=@fakher@
quarkus.datasource.db-kind=@quarkus.datasource.db-kind.pg@
quarkus.datasource.username=@quarkus.datasource.username.pg@
quarkus.datasource.password=@quarkus.datasource.password.pg@
quarkus.datasource.reactive.url=@quarkus.datasource.reactive.url.pg@
quarkus.datasource.reactive.max-size=@quarkus.datasource.reactive.max-size.pg@
quarkus.hibernate-orm.database.generation=@quarkus.hibernate-orm.database.generation.pg@
quarkus.datasource.jdbc.url=@quarkus.datasource.jdbc.url.pg@
