quarkus.vault.url=${VAULT_URL}
quarkus.vault.secret-config-kv-path=@vault.secret.config.path@
quarkus.vault.kv-secret-engine-mount-path=@vault.kv.mount.path@
quarkus.vault.secret-config-kv-path.db=@vault.secret.config.path@
quarkus.vault.authentication.kubernetes.role=@vault.kubernetes.role@

quarkus.datasource.db-kind=${db.kind:postgresql}
quarkus.datasource.username=${db.username}
quarkus.datasource.password=${db.password}
quarkus.datasource.reactive.url=${db.reactive-url}
quarkus.datasource.reactive.max-size=${db.reactive-max-size:20}
quarkus.hibernate-orm.database.generation=${db.hibernate-generation:update}
quarkus.datasource.jdbc.url=${db.jdbc-url}
